### ISSUE TITLE
Listing embeds in admin > assets section takes very long or times out

### ISSUE THREAD

**Issue by andreimoment** [spicywebau/craft-embedded-assets#102]
#### Description

Viewing the embeds folder in the admin section takes very long or times out. There are a total of 43 items in the list, all are youtube embeds. The database is identical on production and dev.

**Currently using the plugin blocks the client-facing site while the thumbnails load in the admin section. This is a serious bug -- the site becomes unavailable for up to a minute every time the admin tries to add an embed to an entry.**

**Production:** CraftCMS 3.0.41.1, plugin v. 1.0.2
**45 seconds to load 43 item list of youtube embeds**
Switching to this asset folder, I see the spinning wheel for 46 seconds on production, and then the list appears. 

**DEV:** CraftCMS 3.0.41.1, plugin v. 2.0.2, also with 1.0.2
**Times Out**
The list does not appear and I see 4 pop-up error messages "unknown error" after 55 seconds of waiting. 

After the failure, the browser js console shows:
```
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
/index.php?p=admin/actions/element-indexes/get-elements:1 

Unchecked runtime.lastError: The message port closed before a response was received.
assets:1 

Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
/index.php?p=admin/actions/element-indexes/get-elements:1 

```

I was planning to update the plugin on production but it is failing on DEV so I will wait for resolution. How can I help you diagnose?

#### Steps to reproduce
1. Upload 43 youtube embeds
2. Switch to the assets folder
3. very slow listing or timeout

Or, click to add an embed to an entry -- the assets dialog behaves in a similar fashion.

#### Other information
- Embedded Assets version: 1.0.2 is very slow, 2.0.2 fails
- Craft CMS version: 3.0.41.1

**Comment by andreimoment** [comment]
I noticed that if I remove the plugin and reload the page, the file list appears instantaneously. This makes me think that the issue is with the thumbnail images which I presume get pulled from the provider (youtube in this case). 

Is there a way to switch these thumbnails off?

**Comment by andreimoment** [comment]
@spicywebau, is there a plan to address this? 

Using the plugin blocks the site including client page while the thumbnails load in the admin section. So the site produces timeouts every time the plugin is used. This is a serious bug.

**Comment by ttempleton** [comment]
Hi @andreimoment,

Embedded Assets v2.0.3 adds the `showThumbnailsInCp` setting.  This setting is enabled by default, but can disable showing embedded asset thumbnails in the control panel when set to `false` in Embedded Assets' config file at `config/embeddedassets.php` (create it if it doesn't exist), for example in the following way:

```php
<?php

return [
    'showThumbnailsInCp' => false,
];
```

Hope this resolves your issue 😃

**Comment by andreimoment** [comment]
With Embedded Assets 2.0.5, with thumbnails disabled it takes over 48 seconds for 49 embedded videos. I experience a long delay and then they all show at once... maybe this is not a thumbnail issue but some kind of delay in the query?

How can I help you debug this?

The 48 second request(s):

```
https://www.site.com/index.php?p=admin/actions/debug/default/view&tag=5d0155...
https://www.site.com/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1
```


For comparison, getting the list of over 300 image assets takes 2 seconds (the built-in Craft image assets with thumbnails on Google Drive).
