### ISSUE TITLE
Listing video assets in admin takes very long or times out

### ISSUE THREAD

**Issue by andreimoment** [spicywebau/craft-embedded-assets#107]
#### Description

When listing embedded assets in the admin section, with Embedded Assets 2.0.5, and with thumbnails disabled it takes over 48 seconds for 49 embedded videos. I experience a long delay and then they all show at once... maybe this is not a thumbnail issue but some kind of delay in the query?

This is related to #102 which was closed before I could verify the effectiveness of the fix (not effective).

How can I help you debug this?

The time consuming request(s):
```
https://www.site.com/index.php?p=admin/actions/debug/default/view&tag=5d0155...
https://www.site.com/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1
```
For comparison, getting the list of over 300 image assets takes less than 2 seconds (the built-in Craft image assets with thumbnails on Google Drive).

#### Steps to reproduce
1. Install craft-embedded-assets
2. upload 50 youtube video assets
3. go to the assets folder dedicated to the embedded assets. The page takes almost a minute or times out, whilst blocking the cms client-side

#### Other information
- Embedded Assets version: 2.05
- Craft CMS version: 3.0.41.1

**Comment by pvldigital** [comment]
Hi @andreimoment,

Looks like there was still some functions that's being executed for thumbnail retrieval even though `showThumbnailsInCp,` was set to false. The attributed to the longer load times of the assets.

I've added a fix and will make a release for it soon.

**Comment by pvldigital** [comment]
v2.0.7 has been released. I'm going to close this issue for now. If the problem still occurs then reopen this issue.

**Comment by andreimoment** [comment]
Verifying that this works, but now ALL asset thumbnails in the CP are gone, including the ones not managed by the plugin. And even when double-clicking an asset, the pop-up does not load the image.
