### ISSUE TITLE
Embedded Button gone

### ISSUE THREAD

**Issue by DavidKabelitz** [spicywebau/craft-embedded-assets#108]
#### Description
The Embedded Button on the left corner to link to an asset disappeared. So right now it's not possible to add a new asset.

#### Other information
- Embedded Assets version: 2.0.8
- Craft CMS version: Craft Pro 3.1.32.1

**Comment by jalendport** [comment]
Having this issue too...

**Comment by rogerdawkins** [comment]
Same here, with 2.0.8 and 3.1.32.1

**Comment by rogerdawkins** [comment]
I've just done some further checking. When I view the Assets page I get a console error relating to main.js in a specific cpresources sub folder. When I check in that folder the main.js file is missing. However, when I copy over the main.js from a previous cpresources sub folder the Embed button then reappears and I can add an Embedded Asset.
I presume the latest 2.0.8 release has introduced this issue.

**Comment by sunscreem** [comment]
Fresh install - same issue. Thought I was going mad.

**Comment by sunscreem** [comment]
I had to go back to release 2.0.6 before it came back. Running craft 3.1.33.

**Comment by pvldigital** [comment]
Hi Everyone,

The issue was related to v2.0.7. I've released v2.0.9 which should fix the issue.

@DavidKabelitz @jalendport @rogerdawkins @sunscreem
