### ISSUE TITLE
Shouldn't be allowed to embed if field doesn't allow json

### ISSUE THREAD

**Issue by timkelty** [spicywebau/craft-embedded-assets#115]
Currently if your field doesn't allow json, the embed button still shows, allows you to use it, and the json file still gets uploaded (though it disappears immediately after adding it).

Ideally, both:

- upload rules for that volume would be followed, so json would be blocked from uploading
- the embed button would be hidden all-together

**Comment by pvldigital** [comment]
will be released in the next update
