### ISSUE TITLE
Vimeo: Could not retrieve embed information.

### ISSUE THREAD

**Issue by moreguppy** [spicywebau/craft-embedded-assets#116]
#### Description
Recently discovered a client has not been able to upload Vimeo embeds any longer.

#### Steps to reproduce
1. Goto entry with asset field, or goto assets folder
2. Tried various vimeo links, no luck
3. Tried other embeddable links (Youtube), no luck

#### Other information
- Embedded Assets version: `2.0.11`
- Craft CMS version: `3.2.10`

**Comment by moreguppy** [comment]
Tried the solution suggested here, but still not working unfortunately: https://github.com/spicywebau/craft-embedded-assets/issues/87

**Comment by cole007** [comment]
We are having similar issues on a client site. 

This looks related to issues reported at https://github.com/mikestecker/craft-videoembedder/issues/22 and https://github.com/oscarotero/Embed/issues/326 which seems to concern remote Vimeo access from Digital Ocean servers. Is your site hosted on Digital Ocean @moreguppy?

**Comment by cole007** [comment]
See fix at https://github.com/mikestecker/craft-videoembedder/releases/tag/v1.1.4 - to do with forcing vimeo to use oembed

**Comment by moreguppy** [comment]
@cole007 thank you, yes it is hosted on Digital Ocean

**Comment by mblode** [comment]
What is the solution? My staging site also hosted on Digital Ocean so do I need to switch plugins for the meantime?

**Comment by cole007** [comment]
@mblode @moreguppy updating the `embed/embed` library to 3.4.2 which this plugin depends on will fix the issue

    composer update embed/embed

**Comment by pvldigital** [comment]
Sorry for the late responsive. I've been really busy with projects + neo.

@cole007 thanks for finding the solution, i'll make a release that requires embed to be `>=3.4.2`

**Comment by moreguppy** [comment]
@pvldigital  I'm still getting the 'Could not retrieve embed information' error after updating.

It seems like there may be another underlying issue specific to my build if it is working for @cole007 

Many thanks for the help though!

**Comment by pvldigital** [comment]
Hi @moreguppy,

Hmm that's strange. Can you send me the composer lock file?

**Comment by timmyomahony** [comment]
I'm also using the latest version `2.0.12` with `embed/embed` on `3.4.2` and noticing this on my Digital Ocean servers + Vimeo specifically. It's sporadic. Sometimes the embed shows the video thumbnail with a 403 forbidden. Might be something to do with their use of their CDN

**Comment by cupcakedream** [comment]
I'm getting a vimeo blocked message with captcha after updating to 3.4.2:

"You have been temporarily blocked
Pardon the inconvenience, but our servers have detected a high number of errors from your connection. To continue, please verify that you are a human"

After verifying captcha chrome crashes with "vimeo refuses to connect".

I'm running on Digital Ocean. Is the fix working for other folks?

**Comment by timmyomahony** [comment]
I don't think so. This is an issue around the web:

- https://github.com/mikestecker/craft-videoembedder/issues/22
- https://github.com/oscarotero/Embed/issues/326
- https://meta.discourse.org/t/vimeo-embed-not-working-on-my-site-due-to-vimeo-server-ip-blacklisting/126479/20

**Comment by pvldigital** [comment]
I've tested it on a couple Vultr servers and it seems to be working correctly. From the threads above, it looks like you might need to get the support to whitelist your ip.

I'll keep looking into it though.

**Comment by ttempleton** [comment]
Closing this issue now; embedding Vimeo videos still seems to be working fine after the library update, and any blocking of server IP addresses by Vimeo is something you would need to contact Vimeo about, and unfortunately not something that Embedded Assets can work around.
