### ISSUE TITLE
Embed button disappears 

### ISSUE THREAD

**Issue by ax2000** [spicywebau/craft-embedded-assets#118]
#### Description
When trying to add an asset, the embed button shows up for a second and then it disappears as soon as the list of assets is loaded.

I've checked for console errors and also in the logs but can't see anything. It's my first time using the plugin so not sure if I'm missing something obvious.

#### Other information
- Embedded Assets version: 2.1.1.1
- Craft CMS version: 3.3.16.3

**Comment by pvldigital** [comment]
Hi @ax2000, 

Does the asset volume allow json? Embedded Assets saves the data as a json file so if a volume doesn't allow json the button is removed.

**Comment by ax2000** [comment]
Thanks for pointing that out @pvldigital .

I've allowed json files to the field as mentioned and can confirm that it fixed my issue. Thanks very much!

**Comment by pvldigital** [comment]
No worries.
