### ISSUE TITLE
Frontend Submission

### ISSUE THREAD

**Issue by ChristopherDosin** [spicywebau/craft-embedded-assets#120]
Is there a way to add those embeded assets via frontend submission for a user?
Unfortunately, I have found nothing to do with it.

**Comment by pvldigital** [comment]
Hi @ChristopherDosin,

By default embedded assets doesn't provide that functionality. What you can do though is use the save action in embedded assets.

If the user is logged in, you can create a form that uses the save controller action to save an embedded asset. The form will need to pass the `url` and `folderId` to the action.

--

You can see the action here:
https://github.com/spicywebau/craft-embedded-assets/blob/272616d4e22e1063ad5a8ce506c799f71b1ffc9f/src/Controller.php#L38

**Comment by ChristopherDosin** [comment]
@pvldigital Ah, of course - Awesome. It's working. Just need to find a way to get the folder UID in the frontend for the specific user, so it's uploaded to the user folder 👍

**Comment by ChristopherDosin** [comment]
One other question: How would i now assign the upload to an assets field from a user? Is there any way to do make this happen @pvldigital ?

**Comment by pvldigital** [comment]
Hi @ChristopherDosin,

Sorry didn't notice this was reopened. 

I'm not sure if there's a way to do that within the front end only. I suggest making a new plugin with a controller for the project and use an ajax call to upload + assign the the media field.

Within the controller you'll be able to use the same save action to create the embedded asset. After that's complete you can query the current user and assign the asset to their account.

**Comment by ttempleton** [comment]
I'll close this issue now, as the questions have been answered, but please let us know if you have any additional questions in the future!
