### ISSUE TITLE
TypeError generated when embedding instagram post

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#121]
As of today, we're getting a TypeError when trying to embed an instagram post;

```
TypeError
Return value of spicyweb\embeddedassets\Service::requestUrl() must be an instance of spicyweb\embeddedassets\models\EmbeddedAsset, null returned
```

Screenshot;

![Screenshot 2020-01-24 at 12 28 37](https://user-images.githubusercontent.com/1286410/73066021-45374f00-3ea5-11ea-841d-4f30bdc1ce5a.jpg)

Craft CMS 3.3.19
PHP 7.2

EDIT: quick update. I did some debugging, turns out the the EmbeddedAsset object doesn't validate anymore in the Service, at line 211:

```
return $embeddedAsset->validate() ? $embeddedAsset : null;
```

I am fairly new with Craft, so I don't know exactly what this validation does, or where to find it. But returning it without validation seems to fix the issue. But, something must be missing, as we get a JS error:

![Screenshot 2020-01-24 at 13 42 20](https://user-images.githubusercontent.com/1286410/73069950-5c7b3a00-3eaf-11ea-898e-4241ce6fa167.jpg)

**Comment by skoften** [comment]
Update; found the cause. The image urls aren't validating anymore, because instagram added base64 images in the JSON object:

![Screenshot 2020-01-24 at 15 27 51](https://user-images.githubusercontent.com/1286410/73076481-7d975700-3ebe-11ea-8849-0329037b6af7.jpg)

And the imageValidator is checking on absolute URL's in EmbeddedAsset.php;

```
[['images', 'providerIcons'], 'each', 'rule' => [ImageValidator::class]]
```
So I temporary commented this one out so we can continu our work :-)

**Comment by dbusck** [comment]
> Update; found the cause. The image urls aren't validating anymore, because instagram added base64 images in the JSON object:
> 
> ![Screenshot 2020-01-24 at 15 27 51](https://user-images.githubusercontent.com/1286410/73076481-7d975700-3ebe-11ea-8849-0329037b6af7.jpg)
> 
> And the imageValidator is checking on absolute URL's in EmbeddedAsset.php;
> 
> ```
> [['images', 'providerIcons'], 'each', 'rule' => [ImageValidator::class]]
> ```
> 
> So I temporary commented this one out so we can continue our work :-)

Thanks for finding the issue, I also have this problem and commenting it out works as a temporary fix until an update.
