### ISSUE TITLE
[FR] Add basic support for GraphQL

### ISSUE THREAD

**Issue by mediabeastnz** [spicywebau/craft-embedded-assets#124]
#### Description
Currently when trying to get data via GraphQL you only have access to whatever the AssetInterface has. Meaning you can't return anything useful for this plugin.

Would be great to add even the most basic of support when possible 🙏

#### Other information
- Embedded Assets version: 2.2.1
- Craft CMS version: 3.4.10

**Comment by pvldigital** [comment]
Hi @mediabeastnz,

Sure we can look into adding GraphQL support for Embedded Assets.

**Comment by sunscreem** [comment]
@pvldigital Any update on this one?

**Comment by pvldigital** [comment]
Hi @sunscreem,

I've been swamped with doing projects so I haven't been able to look at our plugins at all. This means I haven't made any meaningful changes for GraphQL. Thankfully @ttempleton is back and currently maintaining our plugins. I'll let him know about his feature request and will decide how we go from there.

**Comment by joshuabaker** [comment]
@pvldigital @ttempleton We’re reaching a point where we really need to get this working for an upcoming launch. Happy to PR, but being this plugin isn’t a field per se I wasn’t sure what the GQL solution would be. What were you thinking for this?

**Comment by ttempleton** [comment]
I've been thinking about whether we could add an `embeddedAsset` query similar to the existing `asset`/`assets` queries, which would essentially be internally querying for Craft assets using the same arguments, and then converting them to embedded asset data.  I'm not sure how well that would work, but it's the most potentially viable idea that I've thought of at this point.  I definitely welcome any other suggestions for how it could work, though.

**Comment by joshuabaker** [comment]
Thanks for your thoughts, @ttempleton.

I think there’s a few options here...

### Option 1: Add a query

Like you suggest, we could add something to query assets.

The one key issue with approach is that we’d have to send a second GQL request as (currently) Craft has no way of using another query response (à la Apollo Link’s [@export direction](https://www.apollographql.com/docs/link/links/rest/#export-directive)).

```gql
{
  entry(id: 123) {
    ... on xyz_xyz_Entry {
      myAssetField {
        id # 456
      }
    }
  }
}
```

```gql
{
  embeddedAssets(id: [456]) {
    html
  }
}
```

### Option 2: Piggyback an existing query

I’ve not done anything like this, but [SEOmatic](https://github.com/nystudio107/craft-seomatic) has a method that [‘piggybacks’ an existing element query](https://github.com/nystudio107/craft-seomatic/commit/b58e60ca94b159b160a20f9b014d19dc7b27c0bb). This feels very clean to me on the surface.

```gql
{
  entry(id: 123) {
    ... on xyz_xyz_Entry {
      myAssetField {
        embeddedAsset {
          html
        }
      }
    }
  }
}
```

Related issue discussing this: nystudio107/craft-seomatic#483

### Option 3: Introduce a directive

This idea’s a bit more left field, perhaps. A `@contents`, or similarly named, directive could be used to return the contents of the stored JSON. This could be useful outside of the scope of the plugin’s use case, which could be a positive or a negative, depending on how you look at it.

```gql
{
  entry(id: 123) {
    ... on xyz_xyz_Entry {
      myAssetField {
        url @contents(cacheDuration: 86400)
      }
    }
  }
}
```

**Comment by ttempleton** [comment]
Thanks @joshuabaker -- the piggybacking option is excellent, I've had success implementing it today which is now in the [`feature/graphql-support`](https://github.com/spicywebau/craft-embedded-assets/tree/feature/graphql-support) branch.  Will do further testing and make any improvements required over the next couple of days, but as long as no serious issues come up, this will be released at the end of the week.

**Comment by ttempleton** [comment]
Embedded Assets 2.4.0 has just been released with GraphQL support.
