### ISSUE TITLE
Fix PHP 7.4 deprecation

### ISSUE THREAD

**Issue by engram-design** [spicywebau/craft-embedded-assets#127]
There's a deprecation at https://github.com/spicywebau/craft-embedded-assets/blob/master/src/Service.php#L196 with PHP 7.4.

![Screen Shot 2020-04-22 at 9 18 44 am](https://user-images.githubusercontent.com/1221575/79924066-4e22c700-847a-11ea-8713-c8289a627bc0.png)

Should be changed to:
```
$code = ($value instanceof Twig_Markup ? (string)$value : is_string($value)) ? $value : '';
```

**Comment by pvldigital** [comment]
fix has been released in v2.2.1.1
