### ISSUE TITLE
Craft 3.4 Support

### ISSUE THREAD

**Issue by RitterKnightCreative** [spicywebau/craft-embedded-assets#128]
Great plugin!

Are you planning on supporting Craft 3.4?  The new CP does break a few things:

* When using the Preview File dropdown/gear option inside a Volume index for example, Craft shows the json file instead of the preview.  If I use the Edit Asset feature via the menu instead, the Preview does work in the HUD there.
* Clicking on the asset's Title/text goes to Craft 3.4's new asset preview window. The thumbnail of the video works but clicking preview shows the json preview instead.

**Comment by pvldigital** [comment]
Hi @RitterKnightCreative,

I'll have a look into the issues with 3.4 later this week. Currently doing some projects which is taking up most of my time.

**Comment by ttempleton** [comment]
Hi @RitterKnightCreative,

Support for Craft 3.4's asset previews has now been added in Embedded Assets 2.2.2.  Please let us know if there are any further issues.
