### ISSUE TITLE
Is it possible to embed non YouTube Videos?

### ISSUE THREAD

**Issue by laurabennett** [spicywebau/craft-embedded-assets#133]
#### Description
I'm trying to embed a video from PBS
https://video.nhpbs.org/video/call-care-nh-preview-zhhcjz/

#### Steps to reproduce
1. Try to embed asset
2. Warning icon displays with this message "This information is coming from an untrusted source. As a security measure embed codes will not be shown."
3. Image is saved but no video is available 

#### Other information
- Embedded Assets version: 2.2.4
- Craft CMS version: 3.4.20

**Comment by ttempleton** [comment]
Hi @laurabennett,

Thanks for letting us know about this.  Unfortunately, it seems that the embed library Embedded Assets uses doesn't support embedding videos from PBS.

Embedded Assets 2.2.5 now extracts the embed code for sharing the video from the video page, and uses that as the embedded asset's embed code.  At this stage, only the main PBS and NHPBS sites are supported, but as long as other PBS-affiliated sites use the same video player, it should be easy to add support for them in the future.

**Comment by laurabennett** [comment]
Thank you!!
