### ISSUE TITLE
Instagram embed stopped working

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#134]
![Screenshot 2020-05-24 at 13 36 45](https://user-images.githubusercontent.com/1286410/82753173-f999a100-9dc3-11ea-9aaa-e7b13ba79c97.jpg)

![Screenshot 2020-05-24 at 13 38 39](https://user-images.githubusercontent.com/1286410/82753175-facace00-9dc3-11ea-8d3f-90ce34bbd9cf.jpg)

Craft CMS 3.4.15
Embedded Assets 2.2.4

**Comment by ttempleton** [comment]
Hi @skoften,

I'm unable to replicate this, but [Instagram have been locking down their usage by non-members recently](https://mashable.com/article/instagram-requires-log-in-to-view-profiles/), so it would make sense, depending on how many times that server has accessed Instagram recently, that trying to embed another post would give you a login page instead.  Unfortunately, if that's what's happening, I don't think Embedded Assets can do anything about it.

That said, the JavaScript error when it happens isn't ideal, so I'll fix that in the next release.

**Comment by skoften** [comment]
Hm, weird. Have you tries this photo/post: https://www.instagram.com/p/B_QQztfKk12/ ?

This is a public post. I tried embedding it on different server, different IP address same error.

**Comment by ttempleton** [comment]
Yeah, I had tried that post and it worked.  It's strange that you're getting the login page on a different server, though (unless *both* have run into the non-member view limit, I suppose, but the chances of that happening on two of your servers around the same time don't seem great to me).  I'll have a look at it on some other servers and see if it happens.

**Comment by skoften** [comment]
Hmmm. Don't think it's a member view limit, tested on a dev server which doesn't do any requests. 

Is there a way to test it from the CLI of my server, with CURL of something? Any command? Maybe this will give me more info.

**Comment by ttempleton** [comment]
Yeah, using curl should be fine:

```
curl -L -o <filename to save> https://www.instagram.com/p/B_QQztfKk12/
```

If this saves the correct page on a server where Embedded Assets is still getting the login page, we can rule out an issue with view limits.

**Comment by skoften** [comment]
Tries 4 different servers, 3 different locations, all result in a not logged in page. But 3 out of the 4 servers have never made any requests to Instagram. So it seems not a single request is possible without logging in?

**Comment by ttempleton** [comment]
See oscarotero/Embed#357 for the related issue for the Embed library Embedded Assets depends on.  If a fix can be applied and released for version 3 of the Embed library, then we'll update Embedded Assets' minimum requirement and that should fix your issue.  (We are unable to use the newer version 4 at this stage, because that version has a stricter PHP version requirement than Craft has.)

If a fix is released for v4 and not for v3, we will look into alternative solutions for Instagram until we can upgrade to v4 (presumably at the time of the Craft 4 release).

**Comment by ttempleton** [comment]
Embedded Assets 2.2.6 has just been released, which upgrades the minimum requirement for the `embed/embed` library to 3.4.5 which fixes the Instagram embedding issue.
