### ISSUE TITLE
Fail to update from 2.2.6 to 2.2.7

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-embedded-assets#138]
#### Description

`2.2.7` was released yesterday, and since yesterday I'm trying to upgrade from `2.2.6` to `2.2.7`.
This is what was previously in composer.json file: `"spicyweb/craft-embedded-assets": "2.2.6"`
And this is what I tried and failed to update: `"spicyweb/craft-embedded-assets": "v2.2.7"` and `"spicyweb/craft-embedded-assets": "v2.2.7"`.

Each time I got this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package spicyweb/craft-embedded-assets v2.2.7 exists as spicyweb/craft-embedded-assets[0.0.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.1.1.1, 2.2.0, 2.2.1, 2.2.1.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, dev-craft-2, dev-dev, dev-feature/instagram-auto-refresh, dev-feature/replace-button, dev-master] but these are rejected by your constraint.
```

#### Steps to reproduce
1. Try to update from 2.2.6 to 2.2.7
2. Get the update error

#### Other information
- Embedded Assets version: 2.2.7
- Craft CMS version: 3.4.25 and 3.4.26

**Comment by ttempleton** [comment]
Hi @romainpoirier,

Changing it to `"spicyweb/craft-embedded-assets": "2.2.7"` (without the "v" in the version) should be fine to perform the update.

**Comment by romainpoirier** [comment]
Sorry for the copy-paste error, but I was saying that both `"2.2.7"` and `"v2.2.7"` returned (and still returns) the same error.

**Comment by ttempleton** [comment]
Hmm, looks like Packagist didn't update for 2.2.7 when I tagged it.  I've just pushed a commit that seems to have gotten things moving, though.  It should hopefully be working now!
