### ISSUE TITLE
FR: Add support for Vimeo videos with domain restrictions

### ISSUE THREAD

**Issue by Kashkin** [spicywebau/craft-embedded-assets#139]
#### Description
It appears that Embedded Assets doesn't cater for Vimeo videos with domain restrictions.

#### Steps to reproduce
1. Restrict a Vimeo video to a domain
![image](https://user-images.githubusercontent.com/3699310/86685314-86ca4980-c042-11ea-828a-ccf35fb2564c.png)
_Note: I used a client's domain for this example, and their CMS for this test._

2. Try and embed it in Assets
![image](https://user-images.githubusercontent.com/3699310/86686917-e70dbb00-c043-11ea-8b2f-a6020582e941.png)

#### Other information
- Embedded Assets version: 2.2.7
- Craft CMS version: Craft Pro 3.3.20.1

Talking to Vimeo support, they offered the following advice:

> To provide the whitelisted domain in the oEmbed request, the plugin must set a "Referer" header with the value set to your video's whitelisted domain. Here's an example oEmbed request for a video with domain-level embed privacy expressed as a curl:
> 
> `curl -X GET 'https://vimeo.com/api/oembed.json?url=https://vimeo.com/307074610' -H 'Referer: https://example.com'`
> 
> For more information, please take a look at our [oEmbed documentation](https://developer.vimeo.com/api/oembed/videos#embedding-videos-with-domain-privacy)

**Comment by ttempleton** [comment]
Hi @Kashkin,

Could you please try this with the [Embed](https://github.com/oscarotero/Embed/tree/v3.x) library's [version 3 demo site](http://oscarotero.com/embed3/demo) and see if it happens there?  Embedded Assets' Vimeo support is provided using Embed v3, so if it's happening with the demo site I'd recommend opening an issue over there.

**Comment by Kashkin** [comment]
Sure.

It doesn't happen on the demo site, but given that the requests to Vimeo happen server-side, it's hard for me to determine why.

My speculation is that the Embed demo uses the oEmbed library **and** regular requests to build the page. If you just use the oEmbed library to query a restricted video, it returns almost no details, not even the title.

```JSON
{
  "type": "video",
  "version": "1.0",
  "provider_name": "Vimeo",
  "provider_url": "https://vimeo.com/",
  "html": "<iframe src=\"https://player.vimeo.com/video/307074610?app_id=122963\" width=\"640\" height=\"360\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>",
  "width": 640,
  "height": 360,
  "domain_status_code": 403,
  "video_id": 307074610,
  "uri": "/videos/307074610"
}
```

I have made a hotfix that resolves the problem. It's not a good solution, but it should demonstrate the required changes to the embedded asset plugin.

Embed's `create` function allows for a custom [`DispatcherInterface`](https://github.com/oscarotero/Embed/blob/v3.x/src/Embed.php#L65) to be passed in:

```PHP
public static function create($url, array $config = null, DispatcherInterface $dispatcher = null)
```

It is possible to provide [custom headers](https://github.com/oscarotero/Embed/blob/master/src/Http/CurlDispatcher.php#L87) as part of a `DispatcherInterface`.

```PHP
CURLOPT_HTTPHEADER => array("Referer: https://example.com")
```

I've edited this file within `vendor/embed` on the server to include the domain, and Vimeo returns the video's title and thumbnail.

EmbeddedAssets currently doesn't allow for a custom DispatcherInterface to be passed in. I think the solution should be updating the plugin to provide this header for all Vimeo requests.

**Comment by johndwells** [comment]
+1 for this...

I wonder if it's necessary to _only_ set the `CURLOPT_HTTPHEADER` for Vimeo requests, as it may do no harm to set it for any request sent. This would require minimal code changes. 

I'd be happy to make a PR @ttempleton ?

**Comment by ttempleton** [comment]
@johndwells If you'd like to work on a PR for this, we'd be happy to merge it.

**Comment by ttempleton** [comment]
Embedded Assets 2.4.1 is now out with the new `referer` setting as added in #146.  Thanks again @johndwells!
