### ISSUE TITLE
Embed button no longer shows in HUD after upgrading to 2.3

### ISSUE THREAD

**Issue by robmcfadden** [spicywebau/craft-embedded-assets#140]
#### Description

Hi! We recently upgraded to 3.5 beta and the embed button no longer shows in the HUD. It still exists in the main assets view so we can work around this, but it would be nice to have it back in the HUD. Thanks for making such a great plugin!

#### Steps to reproduce

1. Upgrade to 3.5
2. Upload an asset from an assets field
3. Notice the missing Embed button

#### Other information

- Embedded Assets version: 2.3.0
- Craft CMS version: 3.5.0-beta.3
- PHP version: 7.4.7

**Comment by elodiegrondin** [comment]
Hello ! I get the same issue... It would be great to get this button back.
- Craft CMS : 3.4.28.1
- Embedded Assets : 2.3.0

**Comment by ttempleton** [comment]
The button should definitely still be there; with the 2.3.0 update the button was only removed from the Redactor field's 'add image' modal, where it didn't belong anyway.  Are there any JavaScript errors when it doesn't appear?

**Comment by skoften** [comment]
Same issue here. Updated to 2.3.0, embed button disappeared. 

![Screenshot 2020-07-18 at 16 11 17](https://user-images.githubusercontent.com/1286410/87854389-00e7b180-c912-11ea-83a8-8f7557f01f93.jpg)

Downgraded to 2.2.7, button is back.

![Screenshot 2020-07-18 at 16 15 08](https://user-images.githubusercontent.com/1286410/87854394-080ebf80-c912-11ea-969d-7620e32976c2.jpg)

No JS error.

Craft CMS 3.4.28.1

**Comment by robmcfadden** [comment]
I fixed the title of the issue. Sorry about that.

**Comment by ttempleton** [comment]
The button should now be showing again with Embedded Assets 2.3.1 for asset fields with no restriction on allowed file types.
