### ISSUE TITLE
Twitter embeds don't have any styling

### ISSUE THREAD

**Issue by jamiewade** [spicywebau/craft-embedded-assets#147]
#### Description
![Screenshot 2020-10-20 at 17 09 39](https://user-images.githubusercontent.com/6672331/96613637-1ac0d800-12f7-11eb-8b4f-b4f6ca87cc90.png)

There are no console errors.

#### Other information
- Embedded Assets version: 2.4.1
- Craft CMS version: Craft CMS 3.5.13.2

**Comment by ttempleton** [comment]
Which browsers/versions is this happening with?  Firefox in particular will do this to Twitter embeds if it is blocking tracking content.

**Comment by jamiewade** [comment]
@ttempleton Thanks Thomas, yes that seems to be the issue. I was using Firefox and Microsoft Edge (both on Mac, both latest versions) and both had strict protection enabled. When I reduced this, embedded tweets displayed fine in Craft and on the front-end.
