### ISSUE TITLE
Updating to Embed 4

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-embedded-assets#152]
Currently, Embedded Assets uses Embed 3, due to Craft 3's minimum requirement of PHP ~~7.0~~ 7.2.5 (as of Craft 3.6), and Embed 4's minimum requirement of PHP 7.4.  Craft 4 will be updating the minimum PHP requirement to 7.4, though, so we'll be able to update Embed for the Craft 4 version.

**Comment by toyflish** [comment]
@ttempleton is there a feature branch that implements Embed 4 that can be dropped in as a fix for Youtube-consent-banner for people that are on php7.4?

**Comment by ttempleton** [comment]
Working on this in the [`enhancement/embed-4`](https://github.com/spicywebau/craft-embedded-assets/tree/enhancement/embed-4) branch. It's fairly basic at the moment, and most plugin settings and the `BeforeCreateAdapterEvent`'s `dispatcherConfig` property aren't being used yet (hopefully we'll be able to keep most of them, but some may need to be removed).

Some embedded asset properties from Embed 3 aren't provided by Embed 4, so they won't be available for newly-saved embedded assets (though existing embedded assets with these properties will continue to work). These are:
- `type`
- `tags`
- `images`
- `imageWidth`
- `imageHeight`
- `providerIcons`

**Comment by arifje** [comment]
Any news on this one? :-)

**Comment by benfeather** [comment]
Do you happen to have any updates on this? 
Unfortunately, using Embed v3 causes a dependency error with another plugin I'm using that requires Embed v4.

**Comment by scandella** [comment]
Same situation. 
Please let us know if the upgrade is not possible so we can move on to another solution.

**Comment by ttempleton** [comment]
I have just released Embedded Assets 4.0.0-beta.1, for Craft 4 (4.7.0 or later), using Embed 4.

I want to firstly point out that this has been released as a beta because I am not currently able to test some plugin settings (e.g. embed.ly/iframely keys) and therefore cannot confirm that they work; and I am also pretty sure that the Google API key setting does not currently work, due to Embed 4 not supporting rich Google embeds as far as I can tell (or, if it does, I have overlooked how to do it). I may need to work on a Google Maps extractor at some point in the future.

It would be very much appreciated if anyone is willing to try out the release and let me know of any issues. If you choose to try it, you should familiarise yourself with the [changes in this release](https://github.com/spicywebau/craft-embedded-assets/releases/tag/4.0.0-beta.1), and the properties of [`BeforeRequestEvent`](https://github.com/spicywebau/craft-embedded-assets/blob/4.0.0-beta.1/src/events/BeforeRequestEvent.php) if you were previously using [`BeforeCreateAdapterEvent`](https://github.com/spicywebau/craft-embedded-assets/blob/3.2.0/src/events/BeforeCreateAdapterEvent.php). I have tried to make as many Embed 4 settings available to that event as possible; if I have missed anything, please let me know, and I will add it.

I will close this issue now, but if you have any questions about the new release, please let me know here, and if you find a bug, please open a new issue.

**Comment by ttempleton** [comment]
I've also just released 5.0.0-beta.1, for Craft 5, with the same usage of Embed 4, and the same caveats as mentioned above with certain plugin settings that I am unable to test.

**Comment by benfeather** [comment]
I've been using the plugin on both a v4 and a demo v5 site for YouTube videos, and it's working well so far. 
Thank you for updating your plugin, it's an invaluable addition to Craft CMS!

**Comment by arifje** [comment]
Twitter/X embeds don't seem work after updating;

```
#17 {main} {"memory":6936968,"exception":"[object] (Embed\\Http\\NetworkException(code: 47): Maximum (10) redirects followed at /var/www/xxx/cms/vendor/embed/embed/src/Http/CurlDispatcher.php:165)"} 
2024-04-11 15:17:36 [web.INFO] [application] Request context:
$_GET = [
		'p' => 'admin/actions/embeddedassets/actions/preview'
		'showContent' => '1'
		'callback' => 'embeddedassetsbt9f8g5ocde7'
		'url' => 'https://twitter.com/Rhevolver/status/1778271017699291366'
]
```
