### ISSUE TITLE
Could not retrieve embed information.

### ISSUE THREAD

**Issue by lukasreusch** [spicywebau/craft-embedded-assets#153]
#### Description
I've installed Embedded Assets and didn't check any plugin-settings. But for all services (vimeo, youtube, google maps, etc.) I receive a "Could not retrieve embed information." error.

I saw, there are several tickets with problems on Digital Ocean servers. But this is not hosted on DO. It's hosted at german hoster "All-Inkl".

I've created a /tmp in the project-folder and added to absolute path to .env TMPDIR-variable. Didn't help either.

Unfortunately in logs I don't see any errors.

#### Steps to reproduce
1. Install plugin
2. Try to embed any link
3. Error: "Could not retrieve embed information."

#### Other information
- Embedded Assets version: 2.4.4
- Craft CMS version: Craft Solo 3.5.16
--

**Comment by dennisfrank** [comment]
@lukasreusch I have the same issue. Have you found a solution?

**Comment by dmitri-seron** [comment]
I have the same issue.

**Comment by dennisfrank** [comment]
Same here

**Comment by ttempleton** [comment]
This sounds a lot like oscarotero/Embed#411.  I'll echo the advice at https://github.com/oscarotero/Embed/issues/411#issuecomment-741972059 and recommend setting up an Embed demo page on your production server (preferably [version 3](https://github.com/oscarotero/Embed/tree/v3.x), since that's what Embedded Assets currently uses, but if it's an external issue then it shouldn't matter).  Unfortunately, if servers are being blocked by providers, there's nothing Embedded Assets or Embed can do about that.

**Comment by dennisfrank** [comment]
Thanks for the advice @ttempleton. Today I finally managed to try Embed 3.4.15 locally and on the same server as the website. I had no problems in either environment. Embed works, Embedded Assets unfortunately only works locally. 😔  Maybe it will work again with Embed 4.

**Comment by ttempleton** [comment]
Hmm, that does sound more like a plugin issue, then.  Are there any JavaScript errors or any errors returned by your server when it happens?

**Comment by dennisfrank** [comment]
Thanks for reopening this issue.

In fact, an error appears in the console as soon as I try to embed a YouTube video:

```
main.js:formatted:542 Uncaught DOMException: Blocked a frame with origin "https://www.DOMAIN.com" from accessing a cross-origin frame.
    at t.value (https://www.DOMAIN.com/cpresources/284be641/main.js:1:10036)
    at t.value (https://www.DOMAIN.com/cpresources/284be641/main.js:1:10095)
    at t (https://www.DOMAIN.com/cpresources/284be641/main.js:1:12059)
```

![Screen Shot 2021-04-21 at 10 52 02](https://user-images.githubusercontent.com/65968/115526340-369a3c00-a290-11eb-9380-62651292670f.png)

![Screen Shot 2021-04-21 at 10 58 42](https://user-images.githubusercontent.com/65968/115526699-998bd300-a290-11eb-962c-81737ff24274.png)

![Screen Shot 2021-04-21 at 10 59 45](https://user-images.githubusercontent.com/65968/115526986-e8396d00-a290-11eb-9002-6459dc86feb8.png)

**Comment by dennisfrank** [comment]
@ttempleton Were my screenshots with the JS errors helpful? Were you able to look at them or do you need more info?

**Comment by ttempleton** [comment]
Thanks for the info @dennisfrank, unfortunately I haven't been able to reproduce the error.  Does the error still occur if you disable any other plugins you have installed?

**Comment by ttempleton** [comment]
Thanks @klick!
