### ISSUE TITLE
Failed JSON decode leads to an exception

### ISSUE THREAD

**Issue by joshuabaker** [spicywebau/craft-embedded-assets#160]
#### Description

`$decodedJson` is assumed to be a well formed array, however, [`Json::decodeIfJson`](https://github.com/craftcms/cms/blob/5047afec59b9e3d34f33c51192051ac1d962a762/src/helpers/Json.php#L39-L47) can return the original string. This means that if the JSON doesn’t decode we get an exception when accessing `$decodedJson['providerName']`.

https://github.com/spicywebau/craft-embedded-assets/blob/54ed458aac02f099682386b3c2f708ec3ebbf06e/src/Service.php#L170-L172

#### Other information
- Embedded Assets version: 2.4.4
- Craft CMS version: 3.5.17.1

**Comment by joshuabaker** [comment]
Would there be any issue using the `Json::decode` method in the `_getAssetContents` method?

https://github.com/spicywebau/craft-embedded-assets/blob/54ed458aac02f099682386b3c2f708ec3ebbf06e/src/Service.php#L631

**Comment by ttempleton** [comment]
Should be fixed now in Embedded Assets 2.5.0!
