### ISSUE TITLE
Soundcloud embed select player type

### ISSUE THREAD

**Issue by bboy-splendid** [spicywebau/craft-embedded-assets#161]
#### Description
When embedding a soundcloud link there should be a way to select which type of Soundcloud player you would like to use. There are two options, a large background image which stretches the set image, often badly, or a smaller player with a small image to the left and then the player waveform to the right. Embedded assets seems to default to the large image player and I can't see a way to allow users to select between the two options.

I imagine this must also be the case with some other iframe providers.

#### Steps to reproduce
1.
2.
3.

#### Other information
- Embedded Assets version: 2.4.5
- Craft CMS version: 3.6.3

**Comment by ttempleton** [comment]
It looks like SoundCloud returns an iframe that uses the visual style even if you had pasted an embed URL for the classic style.  [SoundCloud's oEmbed documentation](https://developers.soundcloud.com/docs/oembed) makes no mention of setting visual vs. classic style so there's no way to do it at the moment, unfortunately.

It's just a matter of whether `visual=true` is included or not, though, so we could look into expanding the concept of the `getVideoCode()` method, to apply to all embedded assets where the `code` is an iframe, and allow overriding any already-included parameters, so you could set `visual=false`.

**Comment by bboy-splendid** [comment]
That makes sense and would be most flexible for other instances. Many thanks for looking into it!

**Comment by ttempleton** [comment]
Embedded Assets 2.6.0 now includes a `getIframeCode()` method, which can be used to set `visual=false`:

```twig
{% set embeddedAsset = craft.embeddedAssets.get(entry.assetField.one()) %}
{{ embeddedAsset.getIframeCode(['visual=false']) }}
```

Or, if you just need the embed URL, you can use `getIframeSrc()`:

```twig
{% set embeddedAsset = craft.embeddedAssets.get(entry.assetField.one()) %}
{{ embeddedAsset.getIframeSrc(['visual=false']) }}
```
