### ISSUE TITLE
Youtube video doesn't play

### ISSUE THREAD

**Issue by Nielsvdel** [spicywebau/craft-embedded-assets#170]
Possibly related to #168 

![embedded-assets-issue](https://user-images.githubusercontent.com/71633890/114037298-268e5f80-9881-11eb-9034-6d2b16feac6b.png)

#### Other information
- Embedded Assets version: 2.5.2
- Craft CMS version: 3.5.19.1

**Comment by qrazi** [comment]
Same issue here. Opened an issue on Embed repo: https://github.com/oscarotero/Embed/issues/441. 4.x does not have this issue, perhaps this plugin can update to 4.x?

**Comment by nitech** [comment]
Having the same problem. @qrazi what should I do to fix this? Can I do a ´composer install oscarotero/Embed´ to force a newer version of Embed, or wouldn't that work?

**Comment by johnwbaxter** [comment]
@qrazi  Same issue here, when you put in a youtube URL, it says "Before you continue to YouTube" and it looks like there is some kind of cookie screen it wants you to do first! Our clients can't upload any videos at all!

**Comment by qrazi** [comment]
@nitech As mentioned in #152  you can't just bump the version to 4.x.

I did just post a PR on the embed repo that for me fixes the issue. I'm now waiting to see if this is also accepted. If it is and a new release is tagged, a simple composer update should probably work on you Craft projects

**Comment by nitech** [comment]
Thanks @qrazi.

**Comment by hiasl** [comment]
I just found something interesting here at the oembed plugin's issues, which also works for Embedded Assets
https://github.com/wrav/oembed/issues/71#issuecomment-816782824

The error can be workarounded, if you paste the URL like this:
Works : https://youtu.be/2QFrnI0BX4Y. 
Does not work: https://youtube.com/embed/2QFrnI0BX4Y 

Hope this helps some of you and might also be a fix to implement.
