### ISSUE TITLE
Importing to embedded asset fields?

### ISSUE THREAD

**Issue by sonoflee** [spicywebau/craft-embedded-assets#171]
#### Description
Looking for any guidance on importing to embedded asset fields, via Feed Me or other methods.  

I currently have a field in another CMS that just consists of a video URL (youtube or vimeo) and need to pull it in to an entry type in Craft.

#### Other information
- Embedded Assets version: 2.5.1
- Craft CMS version: 3.6.11.2

**Comment by thinkflo** [comment]
@sonoflee  If you are talking about importing to Craft fields that are mapped to Asset fields that are on the same volume used as the Embedded Assets, then you will be able to use FeedMe to import to them no problem.  

If you are talking about the native EmbeddedAssets fields though, then all of those fields are stored in the JSON fields in the file system and not within the Craft database, therefore, you cannot use FeedMe to populate them.  

But, if that's the case, what you can do is use the same schema as an Embedded Assets JSON file and export the required fields to individual JSON files.  Once you have completed creating individual JSON files for all of the fields in the assets that you want to import, just move all the JSON files to the same directory of the Assets Volume where the EmbeddedAssets are stored.  Once you have moved all the JSON files, then you just need to add them to the Craft index by using the Craft CLI tool.  By running `./craft index-assets/all` and that will scan your assets volumes and index any assets that it hasn't seen before which will add all of the JSON files you have just uploaded and make all of your updated fields all now accessible within Craft.
