### ISSUE TITLE
Permissions change since last update?

### ISSUE THREAD

**Issue by robinbeatty** [spicywebau/craft-embedded-assets#172]
I'm using the fetch() api to load embedded assets json files – before the last update (to 2.5.3) this was working fine, but since updating it looks like the permissions of new embedded asset json files is different:

before v2.5.3
new json file permissions: rwxr--r-x

v2.5.3
new json file permissions: rw-------

...which means I get a 403 if I try to fetch. 

Has the permissions changed, or is there a config setting I've overlooked?

- Embedded Assets version: 2.5.3
- Craft CMS version: 3.6.12
- Issue on production environment only, PHP 7.4.16

**Comment by ttempleton** [comment]
No, I'm not really sure what's happened to cause that, but I'm sure it wasn't any change in Embedded Assets; there aren't any changes in 2.5.3 related to file permissions, and the plugin doesn't interfere with the file permissions of saved assets.  [The changes from 2.5.2 to 2.5.3](https://github.com/spicywebau/craft-embedded-assets/compare/2.5.2...2.5.3) were to fix an issue with direct Vimeo embed URLs, and to fix a style issue with embedded asset previews when the embedded asset's `code` contains a `<video>`.
