### ISSUE TITLE
Apollo Codegen for Typescript results in missing sub selection error

### ISSUE THREAD

**Issue by denisyilmaz** [spicywebau/craft-embedded-assets#174]
#### Description
I'm generating typescript types via graphql codegen. While the embedded asset field is working fine in the Craft CMS GraphQL Explorer as soon as i create types it fails to load the query.

The query:
```gql
{
   entries {
      ... on page_page_Entry {
         introImage {
            ... on media_Asset {
              embeddedAsset {
                  __typename
                  html
                  image
                  type
                  imageWidth
                  imageHeight
            }
        }
      }
   }
}
```
#### Steps to Reproduce

1. allow json in asset field
2. add field to graphql query
3. query for entry with embedded asset ffield via apollo
4. apollo throws the error:
5. 
```
Error: Field "embeddedAsset" of type "EmbeddedAssetInterface" must have a sub selection.
Field "embeddedAsset" of type "EmbeddedAssetInterface" must have a sub selection.
Field "embeddedAsset" of type "EmbeddedAssetInterface" must have a sub selection.
```

#### Other information
- Embedded Assets version: 2.5.3
- Craft CMS version: 3.6.12

**Comment by ttempleton** [comment]
Closing this issue now as it appears this was fixed in 2.9.1.
