### ISSUE TITLE
Add no cookie query flag for vimeo embeds

### ISSUE THREAD

**Issue by lukasIO** [spicywebau/craft-embedded-assets#177]
#### Description
In the spirit of #173, I think it would be great if a similar option existed for Vimeo.

For Vimeo the do-not-track policy is appended with a query param:
`https://player.vimeo.com/video/{videoid}?dnt=1`

Reference: https://vimeo.zendesk.com/hc/de/articles/360001494447-Verwendung-von-Player-Parametern

**Comment by ttempleton** [comment]
Sure, we can add a Vimeo option to 2.6 as well.
