### ISSUE TITLE
Instagram pages turn into Login links

### ISSUE THREAD

**Issue by geenious** [spicywebau/craft-embedded-assets#181]
#### Description

I'm probably just missing something, but when I drop in a instagram URL, it just comes out as the "Login Page". Do I need to get an API key or something and add to a settings field?

#### Steps to reproduce
1. Create a new embedded asset and drop in a Instagram link.

#### Other information
- Embedded Assets version: 2.6.1
- Craft CMS version: 3.6.13

**Comment by anandpatel** [comment]
I am experiencing the same issue. Embedded Assets version: 2.5.3

**Comment by ttempleton** [comment]
Instagram does now require an API key which you'll need to add to Embedded Assets' Facebook API key settings field, see #150 for details.
