### ISSUE TITLE
Bump embed/embed package to 3.4.17

### ISSUE THREAD

**Issue by bendesilva** [spicywebau/craft-embedded-assets#183]
I recently made a pull request to the Embed package to implement a fix to the iFramely adapter as it was broken and returning an error on the 3.x branch (had since been fixed in 4.x) – [see pull #449 here](https://github.com/oscarotero/Embed/pull/449). That's been merged into version 3.4.17 which has just been released.

Looks like improvements to the YouTube cookie wall have been implemented in this release too.

Thanks!

**Comment by ttempleton** [comment]
Thanks for the heads up, will make this change in the next release.
