### ISSUE TITLE
Thumbnails on vimeo video changed to default_1280 not the thumbnail provided by vimeo

### ISSUE THREAD

**Issue by johannesSolvr** [spicywebau/craft-embedded-assets#185]
#### Description
Suddenly most videos from vimeo has changed it's thumbnail to https://i.vimeocdn.com/video/default_1280 rather than the thumbnail defined in vimeo. We use the thumbnail as a background image to show the user while the video loads. Now we get colored bars insted. If I add the video again, the thumbnail is correct.

https://www.walleniuswilhelmsen.com/
https://www.cermaq.com/

#### Other information
- Embedded Assets version: 2.8.0 & 2.4.3
- Craft CMS version: 3.7.11 & 3.5.15.1

**Comment by jakedohm** [comment]
We're having this same issue. Seems like a Vimeo API issue or something, as the Thumbnail URLs haven't changed in the JSON, the URLs just stopped working

**Comment by ttempleton** [comment]
Unfortunately, if the provider makes any changes on their end (which I assume is what's happened here if existing thumbnails don't work but re-adding the embedded asset does make them work), it may make some embedded asset data invalid, which I agree is annoying, but isn't really a bug in the plugin. It raises a good point, though, that there should be a way to batch-refresh embedded asset data if this type of situation happens. I've opened a new issue #186 for that proposed feature, so you can subscribe to that issue if you'd like to track its progress.

**Comment by thinkflo** [comment]
I wrote a super ugly but functional script that will go through all of the .json files and call the Vimeo API to retrieve the new thumbnails.  The idea is that you download all of the .json files into a local directory and then put this file in the same directory and run it by issuing a command like `php -q convert.php`

Feel free to modify it for your needs but this helped me in updating over 1100 embedded asset Video Json files with the revised Vimeo Thunbnail

`<?php
$directory = "./";

function thumbsize($url) {
  $ch2 = curl_init($url);

  curl_setopt($ch2, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch2, CURLOPT_HEADER, TRUE);
  curl_setopt($ch2, CURLOPT_NOBODY, TRUE);

  $data = curl_exec($ch2);
  $size = curl_getinfo($ch2, CURLINFO_CONTENT_LENGTH_DOWNLOAD);

  curl_close($ch2);
  return $size;
}

function httpGet($url)
{
    $ch = curl_init();  
 
    $authorization = "Authorization: bearer <vimeo token id>";

    curl_setopt($ch,CURLOPT_URL,$url);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch,CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json', 'Accept: application/json', $authorization ));
 
    $output=json_decode(curl_exec($ch));
 
    curl_close($ch);
    return $output;
}

if (is_dir($directory)){
  if ($opendirectory = opendir($directory)){
    while (($file = readdir($opendirectory)) !== false){
      if (pathinfo("./".$file)['extension'] === 'json') {
        echo "Working with ".$file."\n";
        $data = file_get_contents($file); 
        $obj = json_decode($data);
        $videoId = explode("/", $obj->url)[3];
        preg_match("/\d{9}/", $videoId, $matches);
        //If Vimeo ID format
        if (!empty($matches)) {
          
          $response = httpGet("https://api.vimeo.com/videos/".$videoId);
          $newThumbnail = $response->pictures->sizes[3]->link;
          if (!empty($newThumbnail)) {            
              $thumbsize = thumbsize($newThumbnail);
              $obj->image = $newThumbnail;
              $obj->imageWidth = $response->pictures->sizes[3]->width;
              $obj->imageHeight = $response->pictures->sizes[3]->height;
              $obj->images[0]->url = $newThumbnail;
              $obj->images[0]->width = $response->pictures->sizes[3]->width;
              $obj->images[0]->height = $response->pictures->sizes[3]->height;
              $obj->images[0]->size = $thumbsize;
              file_put_contents($file, json_encode($obj)); 
              echo "Updating Thumbnail: ".$newThumbnail."\n";
              echo "Completed ".$file."\n";
              echo "___ \n";
          }
        }
      }
    }
    closedir($opendirectory);
  }
}
?>`

**Comment by itsmattsoria** [comment]
@thinkflo thanks for sharing this! I'm definitely going to try it for some projects that have a ton of videos on them.

**Comment by thinkflo** [comment]
For those new to this, to retrieve the revised Thumbnails, you'll need to register for a Vimeo API key as an App and authorization with a bearer token.  More info here:

https://developer.vimeo.com/api/authentication
