### ISSUE TITLE
Option to 'refresh' embedded asset data

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-embedded-assets#186]
It would be good to have an option to batch-refresh embedded asset data, if some change on the provider's end causes some part of the existing embedded asset data other than the URL to be invalid (which seems like the cause of #185).

**Comment by jakedohm** [comment]
Subscribing! Thanks for opening this @ttempleton.

I think a pretty decent way to do this would be a console command. If I could run something like `craft embedded-assets refresh --volume="videos"` or something, that would make me really happy!

**Comment by stevecomrie** [comment]
Yeah, this also just hit one of my client sites and I'm staring down the barrel of re-uploading 100+ assets without any seemingly easy way to refresh the video thumbnails.

**Comment by thinkflo** [comment]
@stevecomrie my quick and dirty script

https://github.com/spicywebau/craft-embedded-assets/issues/185#issuecomment-930221389

**Comment by ttempleton** [comment]
Working on this in the [`2.x`](https://github.com/spicywebau/craft-embedded-assets/tree/2.x) branch. I've added console commands as suggested by @jakedohm. They work as follows:

- `craft embeddedassets/refresh/by-volume --volume=embedded` refreshes all embedded assets in the `embedded` volume.
- `craft embeddedassets/refresh/all` refreshes all embedded assets in all volumes.

If anyone would like to try it out, feel free, and please let me know if there are any issues or if you have any other feedback. Hoping to have 2.9.0 out within the next week.

**Comment by ttempleton** [comment]
2.9.0 has now been released with this feature.
