### ISSUE TITLE
How will the new Oembed Read API will effect this plugin?

### ISSUE THREAD

**Issue by arifje** [spicywebau/craft-embedded-assets#187]
I know this plugin uses https://github.com/oscarotero/Embed, but will the deprecation of the old Oembed API and update to Oembed Read will effect this plugin? Trying to some things clear. Thanks!

**Comment by ttempleton** [comment]
If this isn't working with Embed 3 in particular, hopefully we'll be able to fix that in the not too distant future by releasing a new version of the plugin that uses Embed 4. Basic work on it has started, subscribe to #152 for updates on progress.
