### ISSUE TITLE
Version 2.9.2 - composer update failed

### ISSUE THREAD

**Issue by thomasbendl** [spicywebau/craft-embedded-assets#192]
#### Description
installing version 2.9.1 run into following error!
  Problem 1
    - Root composer.json requires benjamminf/craft-embedded-assets 2.9.1, found benjamminf/craft-embedded-assets[dev-feature/instagram-auto-refresh, dev-master, dev-craft-2, 0.0.1, ..., 0.4.1, 1.0.0, 1.0.1, 1.0.2, 2.0.0, ..., 2.x-dev, 3.x-dev] but it does not match the constraint.

#### Steps to reproduce
1. change composer.json "benjamminf/craft-embedded-assets": "2.9.0" -> "benjamminf/craft-embedded-assets": "2.9.1",
2. composer update

#### Other information
- Embedded Assets version: 2.9.0
- Craft CMS version: 3.7.23

**Comment by ttempleton** [comment]
It looks like Packagist hasn't picked up the 2.9.1 tag on the old [`benjamminf/craft-embedded-assets`](https://packagist.org/packages/benjamminf/craft-embedded-assets) page yet. I'm not sure when that will happen, but the update should work now if you change the package to [`spicyweb/craft-embedded-assets`](https://packagist.org/packages/spicyweb/craft-embedded-assets).
