### ISSUE TITLE
Feature request: different caching driver

### ISSUE THREAD

**Issue by arifje** [spicywebau/craft-embedded-assets#198]
Currently this plugin seems to use static file caching only, which is not ideal in load balanced setups. Would be much better if the plugin uses the caching driver that is configured (database, Redis, etc).

Also, it would be nice if we could enable/disable the caching via the plugin config. Because we have multiple webservers, I disabled it in the code. #dirtyhack

<img width="863" alt="Screenshot 2022-03-05 at 16 40 26" src="https://user-images.githubusercontent.com/1286410/156890217-514f5f71-ff44-4e15-80d7-67ff0b685523.png">

**Comment by ttempleton** [comment]
The plugin used to save copies of embedded asset files in `storage/runtime/assets/embeddedassets`, then it was switched over to using Craft's data cache (#158) - but it does fall back to looking for a copy of the file if it isn't in the data cache, and then stores into the data cache and deletes the copy if it was found.

Happy to add a setting to disable embedded asset caching entirely, or maybe just that fallback - let me know what you'd prefer.

**Comment by arifje** [comment]
Hi @ttempleton, thanks for the explanation, sound logical. 

One issue remains: when an embed is refreshed, caching doesn't seem to be cleared, so we are still seeing broken embeds, until we clear caching.

**Comment by ttempleton** [comment]
Ah yep, thanks for pointing that out. Should be fixed now in Embedded Assets 2.10.3.
