### ISSUE TITLE
Feature request: refresh instagram embeds in background (jobs)

### ISSUE THREAD

**Issue by arifje** [spicywebau/craft-embedded-assets#201]
We are experiencing very slow page loading in case instagram embeds are getting refreshed, because this is done syncronized / on page request. 

We have posts that have 5+/10+ and sometimes 20+ instagram embeds included. When this page is requested, reloading the embeds takes up to 60+ seconds. 

Would be nice to have that moved to a background job and added to the queue.

**Comment by ttempleton** [comment]
Fair enough, will have a look at this soon.

**Comment by ttempleton** [comment]
Just released Embedded Assets 2.10.4 with this change.
