### ISSUE TITLE
Vimeo "dnt=1" parameter double-encoded

### ISSUE THREAD

**Issue by sonoflee** [spicywebau/craft-embedded-assets#203]
I have the **"Disable tracking on Vimeo iframes?"** option turned on. 

When using the `getIframeSrc()` method with a Vimeo asset, it looks like that **dnt** parameter is being double-entity encoded - here's an example of the output I am seeing: 

https://player.vimeo.com/video/123456789?app_id=122963&amp;amp;dnt=1

**Comment by ttempleton** [comment]
Thanks for reporting, that should be fixed now in Embedded Assets 2.10.5.
