### ISSUE TITLE
Move refresh function to service and add more options to call

### ISSUE THREAD

**Issue by kringkaste** [spicywebau/craft-embedded-assets#204]
#### Description

Some providers (such as LinkedIn) provide images with an expiration token. After that, the URLs are changing and the old images can no longer be accessed (403). The plugin already has an action on the console that can refresh existing assets.

Would it be possible to move this function into the service as a "Refresh" function and make it callable via ElementAction and variables? Then it can be triggered on various ways and not only by hand. This would be great :)

**Comment by ttempleton** [comment]
I've just added a new service method `refreshEmbeddedAsset()` for the next Embedded Assets 3 release (https://github.com/spicywebau/craft-embedded-assets/commit/bd55978eca792818d224a2106d6a5a250e68a554). Just wanted to ask about an example use case for adding a variable for it?

**Comment by ttempleton** [comment]
Just released Embedded Assets 3.0.2 with the above-mentioned service method. I'll close this issue for now, but happy to take other suggestions for how users can trigger embedded asset refreshing, either as comments in this issue or as a new issue. See also #210 which suggests adding the ability for users to add rules for auto-refreshing of embedded assets.
