### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by fantasticmachine** [spicywebau/craft-embedded-assets#205]
Is there a plan to ensure this plugin will work in Craft 4?

**Comment by ttempleton** [comment]
That's in the [3.x](https://github.com/spicywebau/craft-embedded-assets/tree/3.x) branch. It should be fully functioning, the only reason there hasn't been a beta release yet is that it's still running Embed 3 and I'm not sure if we're going to be able to launch with Embed 4.

**Comment by ttempleton** [comment]
Just released Embedded Assets 3.0.0-beta.1 for Craft 4.0.0-RC2 or later (using Embed 3, but hopefully won't be too long before I can upgrade that).
