### ISSUE TITLE
Embedded Asset not saving to subfolder

### ISSUE THREAD

**Issue by idawgik** [spicywebau/craft-embedded-assets#207]
#### Description
When using Embedded Assets to save a new embed, the json file will always be saved in the root asset location, not in whatever subfolder the assets field is configured for, or selected in the interface. This causes some confusion where a user thinks it wasn't saved/uploaded when it was, just in the root folder, not the subfolder.

#### Steps to reproduce
1. Go to assets location and navigate to a subfolder
2. Embed a video
3. Notice the embedded asset was saved to the root folder, not the subfolder.

#### Other information
- Embedded Assets version: 3.0.0
- Craft CMS version: 4.0.2

**Comment by ttempleton** [comment]
Thanks for reporting this - a bug like this had come up in beta and had been fixed then, but it looks like the format of some data in the page that we rely on to find the right folder has changed in Craft since then. That should now be working again in Embedded Assets 3.0.1.
