### ISSUE TITLE
Feature request: disable refreshing of Instagram embeds by config

### ISSUE THREAD

**Issue by arifje** [spicywebau/craft-embedded-assets#208]
If I am correct, the weekly refresh of Instagram data isn't required if you're using an embed code; this code never changes. Only the preview image expires on a weekly base. So why do a refresh every week in this case if you're not using this image?

We've disabled the refresh manually in the plugin a while ago. and all content seems to work fine after several months. So maybe it's a good idea to create a config variable, which skips or disables this refreshing part; enabled by default, but optionally disabled. 

Thanks!

**Comment by ttempleton** [comment]
The subject of refreshing embedded assets with expired images came up again recently with LinkedIn mentioned in #204, so it might be worth expanding auto-refreshing by adding a way for users to add rules for which embedded assets should be auto-refreshed (e.g. by provider name or URL), along with adding a setting to enable/disable.

**Comment by ttempleton** [comment]
Just released Embedded Assets 3.0.2 with the `enableAutoRefresh` plugin setting (defaults to `true`), which controls whether Instagram embedded assets are auto-refreshed. I've opened #210 for the ability to add rules for auto-refreshing, and once that's done, the `enableAutoRefresh` setting will control whether that is enabled.
