### ISSUE TITLE
The "Uploaded By" field is empty or does not exist after adding the embedded asset

### ISSUE THREAD

**Issue by Ocupe** [spicywebau/craft-embedded-assets#217]
Great plugin, thank you for your work! 👍 

#### Description
When I add an embedded video to my assets, the Uploaded By field does not list the currently logged in user as the creator. This is not a problem for administrative users. But if I restrict users so that they can only see their own assets, then we run into problems. In my current application I have exactly this problem, each user can only see their own uploads. When they upload/add an embedded file, it immediately disappears because the asset is not assigned to the currently logged in user.

Is this a bug or is this intentional? Is there any way to work around this issue?

#### Steps to reproduce
1. Upload a asset in the assets section. (Uploading it in other sections of the app, like direktly from a field, does also not work)
2. I would expect the embedded video to state the currently logged in user under the "Uploaded By" field. But the field is empty or does not exist.

#### Other information
- Embedded Assets version: 2.11.2
- Craft CMS version: 3.7.13

**Comment by ttempleton** [comment]
Thanks for reporting this - it was definitely a bug, and it's fixed now in Embedded Assets 2.11.3.
