### ISSUE TITLE
Where do I set the embedded data?

### ISSUE THREAD

**Issue by wallythewebdev** [spicywebau/craft-embedded-assets#220]
#### Description
Hi - 

I might have misunderstood the docs on where to input embedded data. The use case I working towards is just to embedded Youtube and Vimeo videos . 

I have installed the plugin and expected to find a field to input the embedded data  in the fields section of Craft, but cannot see one for this plugin. 

Is the work flow for using this plugin: 

create a field - 
assign that field to embedded data - 
assign the field to a section - 
add embedded data to the page ? 

If so, I am missing the field option to assign embedded data: 

![image](https://user-images.githubusercontent.com/28821463/191770623-bb780bdd-9b51-484e-90b6-72f6756d24d7.png)

#### Steps to reproduce
1. Downloaded plugin
2. created a field
3. in field type assign plugin (which is not there)

#### Other information
- Embedded Assets version: 3.0.5
- Craft CMS version: Craft Solo 4.2.5.1

**Comment by ttempleton** [comment]
This plugin doesn't add a new field type - embedded assets are regular assets that are saved in JSON format, so you'd just need to have an asset field that (if allowed file types for the field are being restricted) is set to allow JSON assets to be used.

You'd then add embedded assets using the Embed button, next to the Upload Files button on the Assets page, which should look something like this after it's clicked:

![Embedded Assets input screenshot](https://github.com/spicywebau/craft-embedded-assets/blob/3.0.5/docs/assets/input.png?raw=true)
