### ISSUE TITLE
getVideoId not working with Dailymotion

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-embedded-assets#222]
### Bug Description

Add this test URL to embeds: `https://www.dailymotion.com/video/x6yvds`.
The embed is correctly imported, and is showing up. We can see that there are infos in the created JSON.
However, we can't print out the video ID because `embed.getVideoId()` returns nothing.
If trying with a YouTube or Vimeo video, this is working fine: we can get the video using this method.

### Steps to reproduce

1. Prepare embed as usual: `{% set embed = craft.embeddedAssets.get(asset) %}`
2. Try to print the video ID: `embed.getVideoId()`
3. No value

### Embedded Assets version

3.1.0

### Craft CMS version

4.3.6

**Comment by ttempleton** [comment]
`getVideoId()` currently only supports YouTube and Vimeo videos, but Dailymotion support is something we can look at (pull requests welcome too!)

**Comment by romainpoirier** [comment]
It would be super nice if you could integrate it. Thank you 🙏

**Comment by ttempleton** [comment]
That should now be working with Embedded Assets 3.1.1.

**Comment by romainpoirier** [comment]
It works, thank you!
