### ISSUE TITLE
UX: Moving of assets not possible 

### ISSUE THREAD

**Issue by mfell** [spicywebau/craft-embedded-assets#227]
### Bug Description

It's not possible to move assets.

And maybe related to this: It's not possible to create a new asset in a subfolder.

**Originally I have this bug reported in Craft repro**: [Bug Report](https://github.com/craftcms/cms/issues/12957)

- You'll find a video there
- Iwona suggests a solution there

### Steps to reproduce

1. Choose an asset
2. Try to move it into another folder
3. the button (in German "Verschieben") is disabled

Tested under macOS 12.6.x and Chrome.

### Expected behaviour

An enabled button.

### Embedded Assets version

3.1.1

### Craft CMS version

Craft Pro 4.4.4 (first recognition of topic)

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 2.11.4 and 3.1.3.

**Comment by mfell** [comment]
> Thanks for reporting this - fixed now in 2.11.4 and 3.1.3.

Thanks a lot, Thomas! :)
