### ISSUE TITLE
Limit urls by domain (example youtube only)

### ISSUE THREAD

**Issue by mike-moreau** [spicywebau/craft-embedded-assets#230]
### What would you like to see added to or changed in Embedded Assets, and why?

Embedded assets flexibility is super. But there are times I'd like to limit what urls can be embedded: for example, allowing embedded assets of youtube videos only.

What would you think about adding a config option that could limit embeds to only whitelisted domains?

**Comment by ttempleton** [comment]
It hadn't occurred to me until now, but this can be achieved with a combination of overriding the plugin's `whitelist` setting, and enabling the plugin's `preventNonWhitelistedUploads` setting, by setting the following in your Craft project's `config/embeddedassets.php` file:

```php
<?php

return [
    'preventNonWhitelistedUploads' => true,
    'whitelist' => [
        'youtu.be',
        'youtube.com',
        'youtube-nocookie.com',
    ],
];
```

**Comment by mike-moreau** [comment]
Super! Thank you for the reply.
