### ISSUE TITLE
Direct vimeo urls in Craft 4.4.5 don't work

### ISSUE THREAD

**Issue by dbril** [spicywebau/craft-embedded-assets#231]
### Bug Description

When trying to add a direct vimeo (https://player.vimeo.com/external/470169590.hd.mp4?s=0987e36b73f76e044b23cfda3bbbdc18c7bfe470&profile_id=175) url it results in a error message "Could not retrieve embed information". Adding it in a Craft 3.767 environment works fine.

### Steps to reproduce

1. Copy and paste direct vimeo url
2. Plugin is trying to get information
3. "Could not retrieve embed information" is shown in bottom left corner

### Embedded Assets version

3.1.3

### Craft CMS version

4.4.5

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 3.1.4.
