### ISSUE TITLE
Google maps embed only returns a link

### ISSUE THREAD

**Issue by splendidrob** [spicywebau/craft-embedded-assets#232]
Trying to embed a google maps url but embedded assets only returns a link rather than the rich json data for embedding the map. Is this correct or is there a way to use it to fully embed a map? Have tried with various locations and none seem to work?

**Comment by ttempleton** [comment]
You'll need to add an [API key](https://developers.google.com/maps/documentation/embed/get-api-key) to the Embedded Assets settings page in the Craft control panel. You might also need to clear your data caches afterwards for it to work.

If it still doesn't work after that, or if you had already set your API key, could you please provide an example of a URL that isn't working and I'll have a look.

**Comment by splendidrob** [comment]
Ah I see...missed  that in the docs! Thank you.
