### ISSUE TITLE
How to use in module/plugin

### ISSUE THREAD

**Issue by espensgr** [spicywebau/craft-embedded-assets#236]
### What question would you like to ask?

I'm trying to add an api endpoint to Craft and want to get the same info in that as in the Twig template:
```
{% set embeddedAsset = craft.embeddedAssets.get(asset) %}
{{ embeddedAsset ? embeddedAsset.html }}
```
Is that possible and how to do that?
Maybe add a section to det docs regarding this

**Comment by ttempleton** [comment]
That can be achieved with PHP using something like the following:

```php
use spicyweb\embeddedassets\Plugin as EmbeddedAssets;

$embeddedAsset = EmbeddedAssets::$plugin->methods->getEmbeddedAsset($asset);
$html = $embeddedAsset ? $embeddedAsset->html : null;
```
