### ISSUE TITLE
Update embed/embed to v4

### ISSUE THREAD

**Issue by scandella** [spicywebau/craft-embedded-assets#246]
### What would you like to see added to or changed in Embedded Assets, and why?

Don't ask why, but I'm using both `spicywebau/craft-embedded-assets` and `wrav/oembed`!
Recently, `wrav/oembed` has updated its requirement for embed/embed to V4.
But your plugin still use embed/embed 3.4.17.
So now I can't update both plugin!
Is it possible that you require embed v4.x in your next update, or is there a Composer settings to handle this situation?

Best,

**Comment by ttempleton** [comment]
There are plans to upgrade to Embed 4 - see #152, and also see https://github.com/spicywebau/craft-embedded-assets/issues/245#issuecomment-1817312899 for a more recent update on the status of these plans.
