### ISSUE TITLE
Where is the full documentation?

### ISSUE THREAD

**Issue by darylknight** [spicywebau/craft-embedded-assets#252]
### Bug Description

I just inherited a Craft site which uses `getVideoCode` from Embedded Assets. I can see from the latest patch notes that this is getting removed, but I can't see any link in this repository that points at full docs that include this function.
Could you please show me where the docs for this are? The repo has a section on templating, but doesn't include this.

![image](https://github.com/spicywebau/craft-embedded-assets/assets/1250017/138e5903-4908-46eb-a9e0-a21a8937de0f)

### Embedded Assets version

4.0.0

### Craft CMS version

4.8.5

**Comment by ttempleton** [comment]
[Per the changelog](https://github.com/spicywebau/craft-embedded-assets/blob/4.0.0/CHANGELOG.md?plain=1#L47), `getVideoCode()` has been removed in 4.0.0, and `getIframeCode()` should be used instead. `getIframeCode()` is covered in the docs [here](https://github.com/spicywebau/craft-embedded-assets/blob/4.0.0/docs/templating.md#getiframecode).
