### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by KevinBeckers** [spicywebau/craft-embedded-assets#55]
Hi,

Is it possible to translate this plugin?
If so I would like to make the translation to Dutch.

**Comment by benjamminf** [comment]
Definitely late to the party here, sorry about that. I'm always happy to have contributors, and translations are one thing I can't do, so go ahead if you're still willing :)

**Comment by piotrpog** [comment]
@ttempleton, can you add default translation files with english values? So I can easily add my language version.

**Comment by ttempleton** [comment]
@piotrpog A default English translation file has now been added to Embedded Assets 2.4.4.
