### ISSUE TITLE
Failed to save the Asset:“json” is not an allowed file extension.

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-embedded-assets#69]
I would like to use this very cool plugin for the first time. Unfortunately, when I try to add a new embed to Craft assets, I always get this error after clicking on **Save**:

> Failed to save the Asset:“json” is not an allowed file extension.

Why? How can I allow JSON file extension in my assets?
This can be set from an asset field settings, but not from assets settings.

I tried for several sources (Vimeo & YouTube), but always got this error.

- Embedded Assets version: 1.0.2
- Craft CMS version: 3.0.9

**Comment by JayBox325** [comment]
You need to add allowed file types to your Craft config file. See here: https://github.com/benjamminf/craft-embedded-assets/blob/master/docs/installation.md

**Comment by romainpoirier** [comment]
Ooops, sorry 🙊 It works, thank you!
