### ISSUE TITLE
Embedded asset preview jumping around

### ISSUE THREAD

**Issue by jamiewade** [spicywebau/craft-embedded-assets#72]
![bug](https://user-images.githubusercontent.com/6672331/41151039-79b85cd8-6b07-11e8-917e-db27de44904f.gif)

YouTube and Vimeo videos are fine. But Soundcloud and Twitter embeds cause this strange behaviour!

**Plugin Version**: 1.0.2
**Browser**: Google Chrome 67.0.3396.62

**Comment by ttempleton** [comment]
Hi @jamiewade,

I believe that this is the same issue as #65 which has been resolved in Embedded Assets 2.0.0.  If you've updated, could you please confirm whether you still experience this behaviour?

**Comment by jamiewade** [comment]
Hey @ttempleton, I can confirm this issue has been resolved now in 2.0, thank you!
