### ISSUE TITLE
Compatibility with Matrix

### ISSUE THREAD

**Issue by tinchalamo** [spicywebau/craft-embedded-assets#73]
Would be awesome if this could work within the Matrix fieldtype with just the URL field and still display the preview of the embedded asset.

**Comment by Tapiwachin** [comment]
it does work, tested it. in your switch statement use
                 `       {% case "richMediaAssets" %}
                          {% set asset = matrixBlock.richMediaAssets.one() %}
                          {% set embed = craft.embeddedAssets.fromAsset(asset) %}
                          {{ embed ? embed.safeHtml|raw }}`

**Comment by Tapiwachin** [comment]
I'm assuming u have already created a MatrixBlock field, in my case its called richMediaAssets

**Comment by ttempleton** [comment]
We're going to close this issue as Embedded Assets is already compatible with Matrix fields; there doesn't appear to be any difference in how an embedded asset behaves, whether the asset field is in a Matrix block or another element type.
