### ISSUE TITLE
add method to get unique id

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#75]
Would be nice if we could get the Youtube ID instead of complete code.

**Comment by pioneerdesign** [comment]
Another vote to get the ID. Some situations require it.

**Comment by ttempleton** [comment]
This has now been added for YouTube and Vimeo videos in Embedded Assets 2.2.3.  You can get the video's ID from an embedded asset with `{{ embeddedAsset.getVideoId() }}`.
