### ISSUE TITLE
How to access asset data in API / Elements API?

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#76]
I am using Elements API to create JSON feeds with entries, but I can't find any way to display/grab the data from the embedded assets. Any help/examples are appreciated!

https://github.com/craftcms/element-api

**Comment by joshuabaker** [comment]
Something like this...

```php
$embeddedAsset = \spicyweb\embeddedassets\Plugin::$plugin->methods->getEmbeddedAsset($asset);

$data['asset'] = $embeddedAsset ? $embeddedAsset->html : null;
```
