### ISSUE TITLE
Special character in file name makes craft backend broken

### ISSUE THREAD

**Issue by hoangngt** [spicywebau/craft-embedded-assets#79]
Hi, I am using craft-embedded-assets for my page. So far, everything seems to be o.k. but i have small problem with some twitter post with some special characters like **ñ** **ü** **ä**. Your plugin will save the generated .json-file with name exactly the twitter post, something like `Campaña-Fallen-Angels-de-Lynx-Axe-victoria-Station.json`, then when I edit it in craft admin, craft will give out this problem **Internal Server Error**. In Details: 
`2018-09-10 12:24:02 [178.202.118.175][1][mdjbq0stbvoctmo6rsbpkp5v5h][error][yii\base\ErrorException:2] yii\base\ErrorException: fopen(/xxx/Campaña-Fallen-Angels-de-Lynx-Axe-victoria-Station.json): failed to open stream: No such file or directory in /xxx/craft/vendor/league/flysystem/src/Adapter/Local.php:174
`
Could you change your code, so that it will remove/normalize special characters?

**Comment by ttempleton** [comment]
I was unable to reproduce an error when a filename has special characters, but embedded assets will be saved with normalised filenames with use of Craft's [`convertFilenamesToAscii`](https://craftcms.com/docs/3.x/config/config-settings.html#convertfilenamestoascii) setting.
