### ISSUE TITLE
Cannot insert youtube video into redactor editor

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-embedded-assets#80]
Is it possible to insert youtube video inside redactor editor? When i use "insert image" option, asset explorer has option "embed", but pasting youtube link doesnt create new asset on list.

**Comment by msmith7904** [comment]
Same here.

**Comment by ttempleton** [comment]
No, it should not be possible to add an embedded asset into a Redactor field using the add image modal; the embed button appearing there was a bug, and the button will be removed in the upcoming Embedded Assets 2.3.0.
