### ISSUE TITLE
Error while adding assets after upgrade to php7

### ISSUE THREAD

**Issue by martinbroos** [spicywebau/craft-embedded-assets#86]
After server got upgraded to php7 assets can no longer be added, it returns the message asset information can not be retreived.

It causes an error in vendor/benjamminf/craft-embedded-assets/src/Service.php:
`Invalid argument supplied for foreach() line 56` 
`foreach ($pluginSettings->parameters as $parameter)`

After some trying I could solve this by adding a dummy parameter to the settings. So I guess something has changed in php and how this plugin creates  $pluginSettings->parameters.
Could you look into this? Otherwise if someone runs into this issue you can use this workaround.

**Comment by 23d1** [comment]
What did you add to make this work? I added `$dummyparam = 'dummyparam';` but I still get the "Unknown Error"

**Comment by 23d1** [comment]
Where did you add the dummy parameter?

**Comment by martinbroos** [comment]
Yes, in the admin plugin settings. Like this: 
![schermafbeelding 2018-12-13 om 11 06 37](https://user-images.githubusercontent.com/726478/49931487-3cfd9980-fec7-11e8-915b-f52e8691a9c5.png)

**Comment by 23d1** [comment]
Ah, gotcha. Yeah—tried that out and still get errors, so it might be some discrepancies between PHP versions (I get errors on 7.2.13 through 7.3).

**Comment by martinbroos** [comment]
Hmm ok i'm on `php 7.2.11` so this could be a problem for me as well when the server does it's upgrades.

**Comment by 23d1** [comment]
Error persists with 2.0.0

**Comment by ttempleton** [comment]
Thanks for reporting.  This will be fixed in the next release.
