### ISSUE TITLE
Feature Request: video ID var for Twig templating

### ISSUE THREAD

**Issue by adrienne** [spicywebau/craft-embedded-assets#90]
So for videos specifically, i have a common use case that I need just the ID of the video, whether it's a Youtube or Vimeo video or whatever. (That is, just the bit on the end of the URL, like `jEFHK458QJY` is a YT video ID). 

It would be nice if that could be available as a variable. Call it `{{ originalID }}` or something.

**Comment by simpleim** [comment]
We end up with something like this to get the ID for a Vimeo video:

```
{% set embeddedAsset = craft.embeddedAssets.get(entry.bannerVideo.one()) %}

{% if embeddedAsset != null %}
    {% set id = embeddedAsset.url|replace(embeddedAsset.providerUrl, '') %}
    {% if '/' in id %}
        {% set id = id|split('/')[0] %}
    {% endif %}
    <iframe src="//player.vimeo.com/video/{{ id }}?background=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
{% endif %}
```

**Comment by adrienne** [comment]
@simpleim - yeah, i end up with something similar. I'd just rather not have to.

**Comment by ttempleton** [comment]
This has now been added for YouTube and Vimeo videos in Embedded Assets 2.2.3.  You can get the video's ID from an embedded asset with `{{ embeddedAsset.getVideoId() }}`.
