### ISSUE TITLE
PHP error preventing plugin from working - no such file or directory

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#93]
After upgrading to the latest version of Craft (Craft CMS 3.1.1), we can't add embedded assets anymore, caused by this error;

```
2019-01-18 10:06:43 [-][1][-][warning][craft\services\AssetTransforms::deleteAllTransformData] Unable to delete the file "/var/www/site/storage/runtime/assets/sources/28312.json": unlink(/var/www/site/storage/runtime/assets/sources/28312.json): No such file or directory
2019-01-18 10:06:43 [-][1][-][info][application] $_GET = [
    'p' => 'cp/actions/embeddedassets/actions/save'
...
```

I double checked all permissions, but this doesn't seems to be the issue. We can write/upload to all target folders. Also, storage folder is writable, incl. sub dirs.

**Comment by skoften** [comment]
Any idea? We're still unable to use it. Running Craft CMS 3.1.4.

**Comment by ttempleton** [comment]
Hi @skoften, saw your comments in #95 but just wanted to make sure that all issues you were experiencing with Craft 3.1 compatibility have been resolved by the fixes included in Embedded Assets 2.0.0?

**Comment by skoften** [comment]
Hi @ttempleton, tested it on a new site and the plugin works fine!

Is it possible to get in contact with you by mail? We are looking for someone that can expand this plugin with some new features. There's budget. 

Thanks!

**Comment by tonysambell** [comment]
@skoften If you want to discuss paid additional features, you can reach out directly to Spicy Web via info@spicyweb.com.au
