### ISSUE TITLE
As of Craft 3.1, not able to add new embedded assets.

### ISSUE THREAD

**Issue by thisanimus** [spicywebau/craft-embedded-assets#95]
After updating to craft 3.1.x I am unable to add new embedded assets.  
- I can enter a new URL via the "Embed" button, and the plugin fetches the remote asset.
- Clicking "Save" results in nothing, no new asset added, no warning, no alert.

Tested on both local and s3 volumes, and on multiple installations of Craft. Same result each time.

**Comment by jamiewade** [comment]
Can confirm this also. I'm starting to find alternative plugins to this, it's quite clearly not maintained anymore 😞

**Comment by skoften** [comment]
Same here, related to https://github.com/benjamminf/craft-embedded-assets/issues/93 

Did somebody try to contact @benjamminf ?

**Comment by JayBox325** [comment]
This is an issue I'm having on a site that is going live next week. Gutted (but also slightly relieved) it's a global issue.

**Comment by brandonkelly** [comment]
Looks like maybe this has been fixed by https://github.com/benjamminf/craft-embedded-assets/pull/84 ?

You can test by adding @kyle51north’s repo to your `composer.json` file:

```json
"repositories": [
  {"type": "vcs", "url": "https://github.com/kyle51north/craft-embedded-assets.git"}
]
```

And change the `benjamminf/craft-embedded-assets` requirement to `dev-master`:

```json
"require": {
  "benjamminf/craft-embedded-assets": "dev-master as v1.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by nearkingdom** [comment]
Tried this but didn't work for me...

**Comment by skoften** [comment]
@nearkingdom first it didn't work for me also, so I removed the plugin, updated the composer.json again and cleared cp caches afterwards. Then it worked.

**Comment by nearkingdom** [comment]
So I did that and it works - however, the embeds don't get uploaded to where they are meant to go as defined by the field. Very odd.

**Comment by chrisrowe** [comment]
@nearkingdom I believe this is related to https://github.com/benjamminf/craft-embedded-assets/issues/92 that I'm seeing here.

**Comment by chrisrowe** [comment]
Using https://github.com/limesquare-nl/craft-embedded-assets has fixed the issues I was seeing around this.

**Comment by ttempleton** [comment]
#84 has now been merged and will be included in the next release, which should be ready on Monday.

**Comment by ttempleton** [comment]
Embedded Assets 2.0.0 has now been released with the fix for this.  With Embedded Assets now being maintained by Spicy Web, it should be updated from a terminal by running `composer require spicyweb/craft-embedded-assets` and then `composer remove benjamminf/craft-embedded-assets`.
