### ISSUE TITLE
Temporary Uploads folder not deleted on plugin Removal

### ISSUE THREAD

**Issue by yoannisj** [spicywebau/craft-embedded-assets#98]
#### Description
When uninstalling the plugin, the "Temporary Uploads" folder does not get deleted; going to "Assets" stills list it in the list of sources, even if it is empty. I also tried removing the corresponding row in the "craft_volumefolders" table, but it is recreated everytime I visit the "Assets" section in Craft's CP, even after the plugin was fully re-installed, and I ran a `composer install` again to remove the plugin's files.

#### Steps to reproduce
1. Remove all assets in the "Temporary Uploads" folder
2. Uninstall the "Craft Embedded Assets" plugin
3. Go to the "Assets" section in Craft's CP

4. In the db, delete the "Tempoary source" row in "craft_volumefolders" table
5. Go to the "Assets" section in the Craft's CP
6. Reload the "craft_volumefolders" table

#### Other information
- Embedded Assets version:  3.1.18
- Craft CMS version: 2.0.1

**Comment by ttempleton** [comment]
Hi @yoannisj,

This is actually Craft ensuring that the temporary uploads volume exists, not Embedded Assets.  Craft itself uses the temporary uploads volume and automatically creates it with your first manually-created volume.
