### ISSUE TITLE
Custom CSS stretches thumbnail

### ISSUE THREAD

**Issue by benface** [spicywebau/craft-embedded-assets#99]
#### Description

I noticed that after installing this plugin, a portrait image selected in an Assets field:

![pre](https://user-images.githubusercontent.com/1059139/55194299-9ee4c500-517f-11e9-8a93-03ccb67edf29.jpg)

becomes stretched:

![post](https://user-images.githubusercontent.com/1059139/55194305-a60bd300-517f-11e9-92b1-50d1aa891a40.jpg)

I tracked it down to this bit of code in `client/src/main.scss`:

```
// Another fix for Craft asset thumbnails.
//
// The embedded asset thumbnails aren't always the right size (as explained above), and this causes some weird sizing
// issues when switching between thumbnail views.
//
// The following fixes that. I don't know why.
//
.elementthumb > img {
	width: 100%;
}
```

If I remove that `width: 100%` from the `img`, it looks good again.

#### Other information
- Embedded Assets version: 2.0.2
- Craft CMS version: 3.1.20.1

**Comment by dasunr** [comment]
Fixed in Release [v.2.0.6](https://github.com/spicywebau/craft-embedded-assets/releases/tag/2.0.6)
